### ISSUE TITLE
Clear localstorage

### ISSUE THREAD

**Issue by octavioamu** [piotrl/github-profile-card#12]
Hi! I notice when a user is changed the localstorage is not cleared, so the languages are not working, all times are the same.

**Comment by piotrl** [comment]
Hi, thanks for reporting!

Local storage is not cleared, it's true - however it shouldn't affect changing user.
I'm testing different users on [demo page](http://github-profile.com/demo/), and languages section seems to work.

Can you provide more specific steps what you're doing, what you expect and what you see instead?

Thanks!

**Comment by octavioamu** [comment]
Thanks I discovered the problem was between the chair and the monitor. We
actually had the same languages and I found my contribution in a repo made
in Java

**Comment by octavioamu** [comment]
Great, talking about ideas maybe add the option to add a API token, to get
more requests

**Comment by octavioamu** [comment]
I will create and issue about a the token .What do you think?

**Comment by piotrl** [comment]
Sure, feel free.
Later I'll investigate such possibility.
