### ISSUE TITLE
Does not work on https pages

### ISSUE THREAD

**Issue by Giorgi** [piotrl/github-profile-card#26]
As the script is loaded from non https website it is blocked so can you configure your github pages website to use https?

**Comment by piotrl** [comment]
Thanks for feedback, I'll try to configure it :)

**Comment by Giorgi** [comment]
It's very easy to configure and enforce it: [Enforcing HTTPS for your GitHub Pages site](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)

**Comment by piotrl** [comment]
I misconfigured some options in my domain provider panel. Updated them, will see again in 24 hours. :)

**Comment by piotrl** [comment]
https://github-profile.com/ works fine now :)

I'm going to update README with links soon with new default.

**Comment by Giorgi** [comment]
Thanks
