### ISSUE TITLE
null profile name.

### ISSUE THREAD

**Issue by Cshark1** [piotrl/github-profile-card#29]
I have tried to use a github profile card on my website (https://cshark.dev/), but instead of my profile name it says "null" 
![image](https://user-images.githubusercontent.com/53350732/86289035-a0f3ca00-bbf3-11ea-8c89-0dce76fd9f35.png)

**Comment by piotrl** [comment]
hey @Cshark1, thats unfortunate!

I had a quick look, GitHub API returns null. 

Probably you don't have filled in "name" field in GitHub settings: https://github.com/settings/profile

**Comment by Cshark1** [comment]
Ohh, I see, sorry for the trouble, you should add a check for that and if there is no name to use the username, again sorry for the trouble.

**Comment by piotrl** [comment]
Happy to help, take care ;)
