### ISSUE TITLE
Iframe?

### ISSUE THREAD

**Issue by piecioshka** [piotrl/github-profile-card#6]
Cześć @piotrl 

Mam taki pomysł, aby kupić domenę, coś w stylu http://github-profile.com/
gdzie można byłby dostępny Twój widget.

I tak ten kto wejdzie np. tutaj: http://github-profile.com/piotrl widział Twój widget.
Świetny sposób, aby sobie osadzić taki `<iframe>` na stronie.

Z chęcią wykorzystałbym na swojej stronie (https://piecioshka.pl/blog/) widet mojego profilu
http://github-profile.com/piecioshka. Taką mini zajawkę już mam (na dole strony).

Co Ty na to?

**Comment by piotrl** [comment]
@piecioshka super opcja, zrobię to w wolnej chwili. Domena już kupiona :)

Nie wiem czy zdecyduje się na iframe czy tak jak to robi Facebook (skrypt + pusty element do wypełnienia), muszę sprawdzić co jest bardziej developer-friendly.

**Comment by piotrl** [comment]
@piecioshka nie będę robił, ale obecnie do użycia widgetu nie jest potrzebne ręczne wrzucanie plików ani konfiguracja więc efekt jest podobny.

Wystarczy dodać skrypty:
```
<link rel="stylesheet" href="http://github-profile.com/dist/gh-profile-card.min.css" />
<script type="text/javascript" src="http://github-profile.com/dist/gh-profile-card.min.js"></script>
```

i wkleić w porządane miejsce HTML:

```
<div id="github-card"
     data-username="piecioshka">
</div>
```
Demo na: http://github-profile.com/docs/

**Comment by piecioshka** [comment]
@piotrl rozumiem. 

Dzięki za instrukcje jak skorzystać z projektu na swojej stronie 👍
