### ISSUE TITLE
Misleading documentation tag 'username'

### ISSUE THREAD

**Issue by DimitarTasev** [piotrl/github-profile-card#8]
The README.md on the repo says that the JS attribute for settings the username is 'username', however this is incorrect. The proper syntax is 'user**N**ame`. 

The error happens here: https://github.com/piotrl/github-profile-card/blob/master/dist/gh-profile-card.js#L314

**Comment by piotrl** [comment]
@DimitarTasev thanks for reporting that and sorry for inconsistency.

I've updated doc with correct option name.

**Comment by DimitarTasev** [comment]
Thank you for the quick response!
